<h1><center><span style="font-family:Comic Sans MS">Scraping Data About Iphones On Jumia</span><center><h1>

<strong><span style="font-family:Lucida Sans">The aim of this project is to scrape all models of Iphone hosted for sale on the Jumia website. The data gotten from here would be saved in a "csv" format for easy analysis later</span><strong>

In [1]:
#Importing packages

from bs4 import BeautifulSoup as soup
import requests
import pandas as pd
import numpy as np
from time import sleep
from time import time

In [2]:
#First we create sets of empty list to load our data into later 

description =[]
current_prices = []
ratings = []
old_prices = []
brands = []
discounts = []
models = []
stars =[]
# time() is the currnet time at any point of running the code
start_time = time()

# initial request is set to zero and increased by 1 on every successful request
request = 0

#Create a loop to iterate through the pages we would be scraping, in this case 41 pages
for i in range (1,42):
    
    link = "https://www.jumia.com.ng/smartphones/?operating_system=iOS&page={}#catalog-listing".format(i)
    page = requests.get(link)
    request += 1
#  displays each request so we that can monitor the process,not very necessary,you can comment it out.
    #print('request: {}'.format(request))
    
#We parse each request through BeautifulSoup 
    pages = soup(page.text , "html.parser")
    
#We find the class that contains all the information we want to scrape after inspecting the webpage
    containers = pages.find_all('article', class_="prd _fb col c-prd")
#We iterate through every item we want to get and then add it to the empty list we created earlier.
    for container in containers:
        
        #Brands
        brand = container.find('h3', class_='name').text.split(' ')[0]
        brands.append(brand)
        
        #Phone models
        phone_model = container.find('h3', class_='name').text.split(' ')[:3]
        model= ' '.join(phone_model)
        models.append(model)
        
        #Phone Descriptions
        descrip = container.find('h3', class_='name').text.split(' ')[:]
        descriptions= ' '.join(descrip)
        description.append(descriptions)
        
        #Current Prices
        cprice = container.find('div', class_='prc').text.split(' ')[:]
        current_price= ' '.join(cprice)
        current_prices.append(current_price)

#Some products have some value applicable e.g Discount, hence we create an exception that would append "None" if no value was found
        
        #Old Prices
        try:
            oldprice= container.find('div', class_='old').text.split(' ')[:]
            old_price= ' '.join(oldprice)
            old_prices.append(old_price)
        except Exception:
            oldprice = None
            old_prices.append(oldprice)
            
        #Discount
        try:
            dscount = container.find('div', class_='tag _dsct _sm').text.split(' ')[:]
            discount= ' '.join(dscount)
            discounts.append(discount)
        except Exception:
            dscount = None
            discounts.append(dscount)
        
        #Ratings
        try:
            rate = container.find('div', class_='rev').text.replace("(","").replace(")","").replace("5"," ").replace(" "," ")[10:]
            rating= rate.strip()
            ratings.append(rating)
        except Exception:
            rate = None
            ratings.append(rate)
            
        #Number of Stars
        try:

            no_star = container.find('div', class_='rev').text.split(' ')[:1]
            star= ' '.join(no_star)
            stars.append(star)
        except Exception:
            no_star = None
            stars.append(no_star)
            
#We then create a DataFrame to store all the items and values.
Iphones = pd.DataFrame({'Brand': brands, 'Phone Model': models,'Old Price': old_prices,'Discounts': discounts,
                                 'description': description,'Ratings': ratings,'Stars': stars, 'Current Prices':current_prices}, columns =[
        'Brand','Phone Model','Current Prices','Old Price','Discounts','description','Ratings','Stars'])

elasped_time = time() - start_time
print("Completed in {}secs".format(elasped_time))

Completed in 62.97024655342102secs

<span style="font-family:Lucida Sans">We can do a quick view of the Data</span>

In [3]:
#We were able to scrape a total of 2000 items
Iphones

,Brand,Phone Model,Current Prices,Old Price,Discounts,description,Ratings,Stars
0,Apple,Apple NEW Apple,"₦ 20,400","₦ 36,000",43%,Apple NEW Apple Iphone 5 1G RAM 16GB ROM IOS 3...,26,4.3
1,Apple,Apple IPhone 6S,"₦ 74,800","₦ 150,000",50%,Apple IPhone 6S 4.7 Inch 2GB + 64GB 12MP + 5MP...,None,None
2,Apple,Apple IPhone 5,"₦ 20,400","₦ 45,999",56%,"Apple IPhone 5 - IOS 16GB 4.0"" 4G Smartphone -...",7,4.6
3,Apple,Apple IPhone 4s,"₦ 12,000","₦ 41,000",71%,Apple IPhone 4s 3.5Inch -16GB ROM+512MB RAM-8M...,None,None
4,Apple,Apple IPhone 5S,"₦ 28,500","₦ 72,000",60%,Apple IPhone 5S 32GB Gold 4G LTE Without Fing...,1,1
...,...,...,...,...,...,...,...,...
1623,Apple,Apple IPhone 6s,"₦ 89,990","₦ 189,000",52%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1624,Apple,Apple IPhone 6s,"₦ 129,700","₦ 189,000",31%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1625,Apple,Apple 6 Plus,"₦ 89,655","₦ 310,060",71%,Apple 6 Plus 5.5 Inch 1GB + 16GB 8MP + 1.2MP F...,None,None
1626,Apple,Apple Iphone 5,"₦ 31,450","₦ 120,405",74%,Apple Iphone 5 Refurbished Gold 16gb Smart Pho...,None,None
1627,Apple,Apple Certified Refurbished,"₦ 180,000",None,None,Apple Certified Refurbished IPhone 6 64GB Smar...,20,4.3

In [4]:
#A quick view of the first 10 rows
Iphones.head(10)

,Brand,Phone Model,Current Prices,Old Price,Discounts,description,Ratings,Stars
0,Apple,Apple NEW Apple,"₦ 20,400","₦ 36,000",43%,Apple NEW Apple Iphone 5 1G RAM 16GB ROM IOS 3...,26,4.3
1,Apple,Apple IPhone 6S,"₦ 74,800","₦ 150,000",50%,Apple IPhone 6S 4.7 Inch 2GB + 64GB 12MP + 5MP...,None,None
2,Apple,Apple IPhone 5,"₦ 20,400","₦ 45,999",56%,"Apple IPhone 5 - IOS 16GB 4.0"" 4G Smartphone -...",7,4.6
3,Apple,Apple IPhone 4s,"₦ 12,000","₦ 41,000",71%,Apple IPhone 4s 3.5Inch -16GB ROM+512MB RAM-8M...,None,None
4,Apple,Apple IPhone 5S,"₦ 28,500","₦ 72,000",60%,Apple IPhone 5S 32GB Gold 4G LTE Without Fing...,1,1
5,Apple,Apple IPhone XS,"₦ 340,000","₦ 393,800",14%,"Apple IPhone XS Max (4GB RAM, 64GB ROM) IOS 12...",1,3
6,Apple,Apple IPhone 5S,"₦ 27,700","₦ 72,000",62%,Apple IPhone 5S 16GB+1GB- Gold- 4G - 4 Inch- 8...,7,4
7,Apple,Apple Iphone 5,"₦ 21,200","₦ 56,000",62%,Apple Iphone 5 White 16gb Smart Phone Mobile P...,238,3.9
8,Apple,"Apple IPhone XS,","₦ 270,000","₦ 275,000",2%,"Apple IPhone XS, 5.8-inch Super Retina Display...",None,None
9,Apple,Apple IPhone 7-4.7,"₦ 91,690","₦ 400,000",77%,Apple IPhone 7-4.7 Inch Smartphone 2GB+32GB 12...,2,3.5

In [5]:
#A quick view of the last 10 rows
Iphones.tail(10)

,Brand,Phone Model,Current Prices,Old Price,Discounts,description,Ratings,Stars
1618,Apple,Apple IPhone 6s,"₦ 119,700","₦ 189,000",37%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1619,Apple,Apple IPhone 7-4.7,"₦ 115,110","₦ 400,000",71%,Apple IPhone 7-4.7 Inch 4G LET Smartphone 2GB+...,None,None
1620,Apple,Apple IPhone 6s,"₦ 129,700","₦ 189,000",31%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1621,Apple,Apple IPhone 6s,"₦ 90,500","₦ 189,000",52%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1622,Apple,Apple IPhone 5SE-64G+1G,"₦ 78,890","₦ 199,000",60%,Apple IPhone 5SE-64G+1G - 4.0 Inch Screen-12MP...,None,None
1623,Apple,Apple IPhone 6s,"₦ 89,990","₦ 189,000",52%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1624,Apple,Apple IPhone 6s,"₦ 129,700","₦ 189,000",31%,Apple IPhone 6s - 4.7 Inch 4G LET Smartphone 2...,None,None
1625,Apple,Apple 6 Plus,"₦ 89,655","₦ 310,060",71%,Apple 6 Plus 5.5 Inch 1GB + 16GB 8MP + 1.2MP F...,None,None
1626,Apple,Apple Iphone 5,"₦ 31,450","₦ 120,405",74%,Apple Iphone 5 Refurbished Gold 16gb Smart Pho...,None,None
1627,Apple,Apple Certified Refurbished,"₦ 180,000",None,None,Apple Certified Refurbished IPhone 6 64GB Smar...,20,4.3

In [6]:
Iphones.describe()

,Brand,Phone Model,Current Prices,Old Price,Discounts,description,Ratings,Stars
count,1628,1628,1628,1374,1374,1628,291,291
unique,6,91,447,292,75,1081,29,26
top,Apple,Apple IPhone 6,"₦ 20,400","₦ 189,000",51%,"Apple IPhone 6 Plus 16 GB 5.5"" IOS 4G Smartpho...",1,5
freq,1603,230,28,68,187,11,132,103

In [7]:
Iphones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1628 entries, 0 to 1627
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           1628 non-null   object
 1   Phone Model     1628 non-null   object
 2   Current Prices  1628 non-null   object
 3   Old Price       1374 non-null   object
 4   Discounts       1374 non-null   object
 5   description     1628 non-null   object
 6   Ratings         291 non-null    object
 7   Stars           291 non-null    object
dtypes: object(8)
memory usage: 101.9+ KB

In [8]:
#Saving the data as a CSV file
Iphones.to_csv("Iphones.csv", index =False)

<br>

<h2><center><span style="font-family:Comic Sans MS">Thank You For Viewing This Notebook</span><center><h2>